name: Publish

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Clone Repository
      run: |
        git clone https://github.com/NullClock/CubicIDE-gui
    - name: Build & Set CNAME
      run: |
        cd CubicIDE-gui
        npm i
        npm run build
        cd build
        touch ./CNAME
        echo "ide.xcore.tk" > CNAME
        cd ..
        cd ..
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: CubicIDE-gui/build
        target_branch: gh-pages
        verbose: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
